### ISSUE TITLE
Requesting Requirement txt

### ISSUE THREAD

**Issue by KenR22** [neuroethology/BKinD#1]
Hi Thank you for the nice work and for sharing the code
Would it be possible for you to share the package required for the python environment to run this code on?

Thanks

**Comment by jenjsun** [comment]
Thanks for your interest! We will add requirements to the repo soon. 

For now, BKind should work with:
python 3.8 (or higher)
torch 1.9.0 (or higher)
seaborn 
opencv
scikit-learn

Not needed for BKind (Only for testing CalMS21 mouse behavior classifiers in the classifier repo):
tensorflow
tensorflow_addons
pandas

**Comment by jenjsun** [comment]
Apologies for the late response - just added a yml file based on my conda environment https://github.com/neuroethology/BKinD/blob/main/bkind_env.yml so you can use conda env create -f bkind_env.yml

Let me know if there's any issues!
