### ISSUE TITLE
Keypoint discovery

### ISSUE THREAD

**Issue by LjIA26** [neuroethology/BKinD#3]
Hello! 
Great work! 
I was wondering if there was a way to use your model for images instead of videos for keypoint discovery? Thank you.

**Comment by jenjsun** [comment]
Hi! Thanks for your interest - this model would work on images where the main differences between images are the parts you want to track. Notably, videos with stationary backgrounds have this property, but if you had an image collection where this property holds, it would also work. 
Let me know if you have any other questions!

**Comment by jenjsun** [comment]
If there's no other questions, I will close this issue for now.
